// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.mjs",
  },
  datasource: {
    // Comandos de CLI (migrate, db execute, etc.) sempre usam a conexão
    // direta (porta 5432) — o pooler (DATABASE_URL, pgbouncer) não segura o
    // advisory lock que o Prisma Migrate precisa, o que trava `migrate dev`.
    url: process.env["DIRECT_URL"],
  },
});